# Generated by Django 5.2.6 on 2025-11-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='solved_problem',
            field=models.JSONField(default=list),
        ),
    ]
