# Generated by Django 5.2.6 on 2025-11-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_solved_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='solved_problem',
            field=models.JSONField(default=list, null=True),
        ),
    ]
