# Generated by Django 5.2.6 on 2025-10-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='question_count',
            field=models.IntegerField(default=0),
        ),
    ]
