# Generated by Django 5.2.6 on 2025-11-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_solved_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='solved_problem',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
