# Generated by Django 5.2.6 on 2025-11-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='문제 제목', max_length=100)),
                ('description', models.TextField(help_text='문제 설명')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
                ('example', models.JSONField(default=list, help_text='문제 예제(테스트 케이스) 목록')),
                ('conditions', models.JSONField(default=list, help_text='문제 조건 목록')),
            ],
        ),
    ]
