# Generated by Django 5.2.6 on 2025-11-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_problem_answer_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(default=1, help_text='문제 난이도'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='answer_count',
            field=models.IntegerField(default=0, help_text='맞춘 사람'),
        ),
    ]
