# Generated by Django 5.2.6 on 2025-11-16 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_problem_difficulty_alter_problem_answer_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='문제 생성 일자'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='ip',
            field=models.GenericIPAddressField(help_text='문제 작성자 IP주소'),
        ),
    ]
